### ISSUE TITLE
Не собирается на Windows

### ISSUE THREAD

**Issue by nonliable** [superhacker777/hikka#1]
Поставил MinGW, поставил Go. Не собирается ни через go run, ни через make windows. Пробовал на Маке, на Windows x86, на Windows x64. Разные ошибки, результат один. Самое большое, что получилось, - запустить go run. Тогда программа ругалась на отсутствие hcnetsdk.h. Скачал его, положил в папку. Результат - куча ошибок, отсутствие компиляции. Это у меня проблема или сама программа сырая? Я довольно-таки наугад пробовал, потому что не силён в этих языках и Линуксе. Не могли бы вы попробовать скомпилировать для Шиндошс у себя и выложить?

**Comment by superhacker777** [comment]
Установка MinGW на Windows полна боли и печали. Я как-то давно пробовал, забросил это дело на установке переменных окружения. Скорее всего, именно в них и дело, так как система не знает, где ей искать компилятор.

Что касается сборок, я их выкладываю в треде время от времени.

**Comment by gooddemon** [comment]
superhacker777 не могли бы Вы подсказать, как вообще собрать "это" вод виндой ? Мучаюсь, мчаюсь... толку 0 :/

**Comment by superhacker777** [comment]
> как вообще собрать "это" вод виндой ?

Я не знаю. Мне не приходилось этого делать. Если кто-то сможет разобраться во всем этом, я буду рад узнать все шаги этого процесса в подробностях, чтобы добавить всё это в Readme.

**Comment by gooddemon** [comment]
Спасибо за ответ !

**Comment by MeMO82** [comment]
Все работает. Нужно использовать сборку msys2 (стандартную сборку mingw запустить не получилось).

**Comment by Sharabaddin** [comment]
Может собирать на линуксе и выкладывать как релиз под винду?
