### ISSUE TITLE
Please add arm support

### ISSUE THREAD

**Issue by megapro17** [superhacker777/hikka#11]
Будет удобно сканировать через телефон

**Comment by superhacker777** [comment]
> Будет удобно сканировать через телефон

_Не будет._

А вообще, у них на сайте нет библиотек, собранных для ARM. Ходят слухи, что их по почте можно попросить, но я такой херней заниматься точно не буду. Если у кого-то есть желание — велкам, запиливайте и оформляйте pull request.

Кроме того, я не стал оставлять поддержку 32-битных архитектур, так как для этого нужно было бы что-то получше моего колхозного Makefile, но если кто-то желает навести порядок в проекте — велкам тоже.

**Comment by megapro17** [comment]
Вот 32 битная поддержка была бы очень кстати, т.к. через эмулятор Windows XP неплохо фурычит. А 64 эмулировать будет вечность. Или, если смогу достать библиотеки arm, добавишь поддержку? 
Мне удобно т.к. для сканирования локальной сети нести ноутбук не очень практично, а через телефон самое то.

**Comment by superhacker777** [comment]
@megapro17 окей, попробуй достать либы для начала. Я все равно постепенно прикручиваю либы других производителей, так что и этим могу заняться по пути.

> через эмулятор Windows XP неплохо фурычит

Ты, похоже, в какой-то ужасной ситуации находишься, раз рассматриваешь такие извращения. Брутфорс будет со скоростью арифмометра. Впрочем, твоё дело.

**Comment by megapro17** [comment]
Скинул на почту

**Comment by superhacker777** [comment]
@megapro17 мне ничего не пришло.

**Comment by megapro17** [comment]
@superhacker777 
теперь пришло

**Comment by N00bino** [comment]
Тоже хотелось бы попробовать arm сборку. Не только для телефонов ведь... Raspberry, Orange и иже с ними были бы очень рады...

**Comment by superhacker777** [comment]
@megapro17 принял. Сроки называть не буду, потому что я всегда с ними проебываюсь.

@N00bino я тоже думал об этом сразу, но, вроде, андроидовский EABI несовместим с линуксовым, а значит и либы там тоже несовместимы. Если о либах для Андроида хоть что-то можно нагуглить, то для Raspberry Pi уже вообще ничего нет. Опять же, можно у узкоглазых попросить, но что-то мне подсказывает, что не дадут.

**Comment by unknown-anon** [comment]
@megapro17 Мне тоже на почту кинь плиз, попробую допилить хикку до arm
unknown.anon.mail@gmail.com

**Comment by megapro17** [comment]
@unknown-anon
Получилось?
