### ISSUE TITLE
Ports?

### ISSUE THREAD

**Issue by DrDragonFX** [superhacker777/hikka#15]
How to change the port in hikka ? The program does not work with other ports, only 8000! How to change the port 8000 to hikka? For example, I want 80 or 8080 or 37777 or 34567. The program downloaded already ready, it contains files: (start.bat) (hikka.exe) (hcnetsdk.dll) (HPR.dll) (hosts) (logins) (passwords). How do I change the port 8000? All other ports scanned in (vnc_scanner_gui.exe) the program ignores not only works with the 8000. How to change the port 8000 to let's say 37777?

**Comment by megapro17** [comment]
RTFM noob

**Comment by DrDragonFX** [comment]
RTFM. Пошёл нахуй! Не надо тут выёбываться, можно подумать ты с первого дня рождения всё знал... Вместо этого мог бы помочь разобраться, а не строить из себя крутого, ты не крутой, ты мудак! Может в этом деле я и нуб, зато хорош во многих других делах в которых нуб ты!

**Comment by DrDragonFX** [comment]
Если тебе впадлу объяснить, то иди нахуй и не выёбывайся тут передо мной. Нашёлся блять невъебенный знаток программирования.

**Comment by Sharabaddin** [comment]
Спокуха ребята. Попробуй в таком формате 7.7.7.7:1234. Если не получиться то скорей всего программа заточена под 8000 порт(так как он самый популярный для камер наблюдения которые работают через Хиквизион).

**Comment by DrDragonFX** [comment]
"Попробуй в таком формате 7.7.7.7:1234"

Sharabaddin. Такой метод не работает. Hikka попросту тут же закрывается.
Если взять готовый список ip с портом например 7000 никакого результата не будет. Hikka попросту не распознаёт сторонние порты. Но у неё есть команды, каким образом они работают разобраться сложно.

Вот список!
-bf-threads int Bruteforcer threads count (default 1)
-check Check cameras (experimental and not fully tested, but very useful)
-csv string Write result to CSV
-json string Write result to JSON
-logins string A file with a list of logins to bruteforce (default "logins")
-m3u string Write result to m3u playlist
-passwords string A file with a list of passwords to bruteforce (default "passwords")
-port int Camera service port (default 8000)
-shoots string Download pics from cameras into a folder
-threads int Threads count (default 1)

В скачанной версии есть start.bat в котором прописано следующее: hikka -threads 200 -check -shoots pics
Таким образом запускается hikka cо значением -threads 200 которое можно изменить.
Но команда для смены порта отсутствует. Каким образом она должна подставляться неизвестно.

Если добавить вначале списка всех команд       -port 7000      никакого результата не последует. 
Пример: hikka -port 7000 -threads 200 -check -shoots pics 

Если добавить в конце, hikka -threads 200 -check -shoots pics -port 7000 то вроде бы как всё работает, но результатов проверки по прежнему нет, как и в случае со стандартным набором команд. hikka -threads 200 -check -shoots pics

Вот и возникает вопрос. Как заставить Hikka сканировать ip адреса с портом 7000 ???

**Comment by superhacker777** [comment]
Всё работает, но на ваших портах нет совместимых камер.
