### ISSUE TITLE
Баг: Говорит что нет камер и не делает картинки, а на самом деле камер 5 штук и широкий канал

### ISSUE THREAD

**Issue by unknown-anon** [superhacker777/hikka#2]
Вот пример IP на котором воспроизводиться баг: admin:12345@209.115.181.198 port 8000

Баг заключаеться в том что hikka говорит что на ip камер нет, а их там 5 штук, судя по всему камера какогото неизвестного хекке типа, поэтому она так реагирует, плюс еще пробовал запускать на ivms-bf, на этой камере он виснет намертво, даже если флаг -с есть

Баг воспроизводиться всегда, т.е. это не из за проблем с каналом с моей или камеры стороны, в программе iVMS-4200 камера прекрасно работает в прямом эфире и записи показывает.

> $ echo "209.115.181.198" > hosts && ./hikka -check=true -port=8000 -threads=50 -shoots="pictures/"
> Loaded 14 logins
> Loaded 100 passwords
> Starting work in 50 threads

> Logged in: admin:12345@209.115.181.198
> No cameras on 209.115.181.198

ivms-bf уходит в бесконечный цикл:
> $ ./ivms-bf -c -s pictures/ 209.115.181.198
>

Скриншот камер в iVMS-4200
http://prntscr.com/7bshyu

**Comment by superhacker777** [comment]
Исправлено. Та же ошибка могла бы быть и в iVMS-4200, и в примере к SDK, но азиатов спасло только то, что они косячили с уровнями вложенности в коде.

**Comment by Firdavsbek07** [comment]
У меня постоянно выдает сообщение что получится скачать скриншот, что делать?
