### ISSUE TITLE
Can't log into

### ISSUE THREAD

**Issue by rass89rus** [superhacker777/hikka#4]
Привет,

Такое дело, роутер не отвечает на пинги, но порты rtspd http пропрошены и открыты. hikka соответственно пишет Can't log into ... Я с go не очень, можно как-то подкрутить этот момент? И еще одно, при сборке под линух make ругаеться на либу libhcnetsdk.so. Помогает если скопировать ее из проекта ivms-bf, тогда норм.

**Comment by superhacker777** [comment]
Скорее всего, камера просто несовместима с камерами тех производителей, для которых делался мой брутфорсер. 

31.01.2016, 05:32, "rass89rus" <notifications@github.com>:

**Comment by rass89rus** [comment]
Камера Hikvision, это я тупанул, не разобравшись до конца, все работает.  hikka просто пишет Can't log into когда не находит пароль, глянул  wireshark'ом на происходящее все норм.

**Comment by rass89rus** [comment]
Еще вопрос, сколько максимально потоков (bf-threads) можно долбить в один регистатор, что-бы максимально ускорить перебор и рег не умер? В моем случае нужно перебрать словать, в нем 1100000 слов. Выставил bf-threads=30, больше стремно. При таком раскладе, процесс займет  ~7 дней.

**Comment by superhacker777** [comment]
Полностью зависит от качества соединения и от железа камеры. Больше 25 я бы не рекомендовал.

02.02.2016, 04:38, "rass89rus" <notifications@github.com>:

**Comment by rass89rus** [comment]
Последний вопрос. Можете добавить вывод в терминал сколько паролей уже перебралось из общего количества. Типа такого 576/1000. Просто при большом словаре, когда брут стоит больше суток, хочеться знать на какой стадии брут жив ли регистратор, или если вдруг что-то с сетью, то  потом хз или заново начинать или забить на все.
