### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by bcskda** [superhacker777/hikka#6]
При вызове make:

src/hikka.go:108:30: error: argument 3 has incompatible type
    (*C.NET_DVR_JPEGPARA)(unsafe.Pointer(&imgParams)),
                              ^
src/hikka.go:200:31: error: argument 5 has incompatible type
   (*C.NET_DVR_DEVICEINFO)(unsafe.Pointer(&device)),
                               ^
make: *** [linux] Ошибка 2

**Comment by superhacker777** [comment]
Какой дистрибутив, какая версия Go, какая версия GCC?

`$ uname -a`
`$ go version`
`$ gcc --version`

**Comment by bcskda** [comment]
Linux 3.16.0-71m, Ubuntu 14.04
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by superhacker777** [comment]
@bcskda удали gccgo (`# apt-get remove gccgo`) и установи нормальный Go 1.6, как здесь расписано: https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04

Должно завестись.

**Comment by bcskda** [comment]
Да, спасибо, завелось
