### ISSUE TITLE
Сборка

### ISSUE THREAD

**Issue by deshume6** [superhacker777/hikka#7]
Приветствую. В ходе поисков брута для iVMS наткнулся на вас. Я чайник в программировании, не понял как, в общем, запустить все это дело для брута. У меня Windows 32 bit. Какие мои дальнейшие действия? Что скачать, что прописывать?

**Comment by superhacker777** [comment]
> 32 bit
No way.

17.06.2016, 09:52, "deshume6" <notifications@github.com>:

**Comment by Heatlessguy-ipxkz** [comment]
Подними Sygwin, или через CMake сделай себе мэйкфайл. Если интересует готовый бинарник наверняка можно найти в интернете
