### ISSUE TITLE
/usr/bin/ld: cannot find -lhcnetsdk

### ISSUE THREAD

**Issue by ContzZz** [superhacker777/hikka#8]
Привет. Подскажи, пожалуйста, если можешь.
У меня вот такая ошибка 

```
GOOS=linux CGO_CFLAGS="-I/home/contzzz/hikka/include" 
CGO_LDFLAGS="-L/home/contzzz/hikka/lib/Linux -Wl,-rpath=/home/contzzz/hikka/lib/Linux
 -lhcnetsdk" go build -ldflags "-s -w" -o build/Linux/hikka src/hikka.go
# command-line-arguments
/usr/bin/ld: skipping incompatible /home/contzzz/hikka/lib/Linux/libhcnetsdk.so 
when searching for -lhcnetsdk
/usr/bin/ld: cannot find -lhcnetsdk
collect2: error: ld returned 1 exit status
Makefile:9: ошибка выполнения рецепта для цели «linux»
make: *** [linux] Ошибка 2
```

Гуглил по этому поводу но ничего не помогло из того что там писали. Или я калека просто лютая. Может ты знаешь как это исправить ?
Linux  4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 i686 i686 GNU/Linux
go version go1.6.2 linux/386
gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413

**Comment by superhacker777** [comment]
> i686
Я выпилил 32-битные библиотеки. Собирается и работает только под x86_64.
